# Database Configuration
db.url=jdbc:mysql://localhost:3306/blood_donation_system1?allowPublicKeyRetrieval=true&useSSL=false
db.user=
db.password=

# Email Configuration (mock)
email.smtp.host=smtp.gmail.com
email.smtp.port=
email.user=
email.password=your-password
