# Database Configuration
db.url=jdbc:mysql://localhost:3306/blood_donation_system1?allowPublicKeyRetrieval=true&useSSL=false
db.user=root
db.password=thanu@1234

# Email Configuration (mock)
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.user=union20032003@gmail.com
email.password=your-password