# Database Configuration
db.url=jdbc:mysql://localhost:3306/blood_donation_system1?useSSL=false
db.user=root
db.password=Thamil

# Email Configuration
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.user=union20032003@gmail.com
email.password=your-app-password
email.recipient=blooddonationsystem1@gmail.com